### ISSUE TITLE
UnboundLocalError: local variable 'siblings' referenced before assignment

### ISSUE THREAD

**Issue by anujsaraswat741** [kochkinaelena/branchLSTM#17]
<pre>(branchlstm) <font color="#4E9A06"><b></b></font>:<font color="#3465A4"><b>~/Desktop/branchLSTM</b></font>$ python preprocessing.py 
[nltk_data] Downloading package punkt to
[nltk_data]     /home/Desktop/branchLSTM...
[nltk_data]   Package punkt is already up-to-date!
Loading the model
Done!
Traceback (most recent call last):
  File &quot;preprocessing.py&quot;, line 594, in &lt;module&gt;
    preprocess_data()
  File &quot;preprocessing.py&quot;, line 438, in preprocess_data
    train_dev_split = load_dataset()
  File &quot;preprocessing.py&quot;, line 185, in load_dataset
    branches = tree2branches(conversation[&apos;structure&apos;])
  File &quot;preprocessing.py&quot;, line 213, in tree2branches
    i = siblings.index(node_name)  # index of a current node
UnboundLocalError: local variable &apos;siblings&apos; referenced before assignment
</pre>

The preprocessing.py runs fine on RumorEval 17 but gives this error while running it on PHEME Dataset.

**Comment by kochkinaelena** [comment]
Hi,

Which python version are you using?  Have a look at the preprocessing code [here](https://github.com/kochkinaelena/RumourEval2019/blob/master/preprocessing/tree2branches.py), which works with Python 3 and should resolve this error.

**Comment by anujsaraswat741** [comment]
Hi, 

I'm using python 2.7 and I also tried the python 3 preprocessing code as mentioned by you, it's still giving the same error when I run it on the PHEME dataset. 

I need stance labels for the PHEME dataset using branch LSTM, could you please upload the stance labels used in NileTMRG while evaluating on PHEME dataset as mentioned in your paper titled " All in one: Multi-Task Learning for Rumor Verification". 

Thanks

**Comment by kochkinaelena** [comment]
This error in the original code can happen because the code comes across an unusual structure file in the PHEME dataset that was not present in RumourEval and thus it is not accounted for in the code. So to fix it, you need to look at the particular conversation that breaks the code and understand what is different about it and implement the necessary changes.

[This](https://github.com/kochkinaelena/RumourEval2019/blob/master/preprocessing/tree2branches.py) code assigns variable siblings = None at line 16, so it would not produce exactly the same error. I would recommend you to look more into the differences between the two versions of preprocessing (such as checking `if siblings is not None:` at [line 30](https://github.com/kochkinaelena/RumourEval2019/blob/master/preprocessing/tree2branches.py#L30) ) and that should help you save your issue.
